appName: ''
appUniqueId: ''
appInfo:
  description: ''
  appVersion: 1.0.1
  appRepoUrl: ''
  appIconUrl: ''
  appAuthorUserId: ''
  forkedFrom: ''
technicalInfo:
  supportedLanguages: []
  supportedFrameworks: []
  secrets: []
  services: []
  knowledgebases: []
  instruction: []
usage:
  develop:
    run: []
    agents: []
    layout: ''
  install:
    steps: []
    customInstallationAgent:
      enabled: false
      agent: ''
  appUse:
    prerunsteps: []
    agents: []
    layout: ''
    appPreview:
      type: ''
